Repository yalelibrary/yul-dc-management, pull requests merged in 2020-09, with the labels that each got.

#253 I542 csv with multiple sources
  app/models/mets_xml_import.rb
  app/models/oid_import.rb
  app/services/metadata_cloud_service.rb
  spec/fixtures/short_fixture_ids_with_source.csv
  spec/models/oid_import_spec.rb
  spec/services/metadata_cloud_service_spec.rb
Labels: Technical Enhancement

#266 More ptiff cleanup
  app/lib/pyramidal_tiff_factory.rb
  spec/lib/pyramidal_tiff_factory_spec.rb
Labels: Bugs

#278 Ensure METADATA_CLOUD_HOST is not set to empty string
  app/services/metadata_cloud_service.rb
  spec/services/metadata_cloud_service_spec.rb
Labels: Bugs

#284 Paginate and resolve all for notifications
  Gemfile
  Gemfile.lock
  app/controllers/notifications_controller.rb
  app/models/notification.rb
  app/models/parent_object.rb
  app/views/notifications/index.html.erb
  config/routes.rb
Labels: Feature

#302 I608 clickable oids
  app/controllers/parent_objects_controller.rb
  app/datatables/parent_object_datatable.rb
  app/views/parent_objects/index.html.erb
  spec/datatables/parent_object_datatable_spec.rb
  spec/support/datatables_helper.rb
Labels: Technical Enhancement
