Repository yalelibrary/yul-dc-management, pull requests merged in 2020-07, with the labels that each got.

#137 Add an OID minter service and controller
  app/controllers/oid_minter_controller.rb
  app/services/oid_minter_service.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/routes.rb
  spec/requests/oid_minter_request_spec.rb
  spec/services/oid_minter_service_spec.rb
Labels: Features

#141 322 Authenticate oid request
  Gemfile
  Gemfile.lock
  app/controllers/oid_minter_controller.rb
  app/models/user.rb
  config/environments/development.rb
  config/initializers/devise.rb
  config/locales/devise.en.yml
  config/routes.rb
  db/migrate/20200709205615_devise_create_users.rb
  db/schema.rb
  db/seeds.rb
  spec/factories/users.rb
  spec/models/user_spec.rb
  spec/rails_helper.rb
  spec/requests/oid_minter_request_spec.rb
  spec/support/auth_helper.rb
Labels: Technical Enhancement

#167 remove sourcemaps from Webpack
  config/webpack/production.js
Labels: Bugs

#160 Seed production and dev on load, run OID Minter on seed
  app/services/oid_minter_service.rb
  db/seeds.rb
  ops/nginx.sh
Labels: Technical Enhancement
